name: curvenote
on:
  pull_request:
    branches: ['main']
permissions:
  contents: read
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/publish.yml@v1
    with:
      monorepo: false
      id-pattern-regex: '^ubcgif-(?:[a-zA-Z0-9-_]{3,40})$'
      enforce-single-folder: false
      preview-label: paper
      submit-label: true
      venue: appliedgeophysics
      collection: presentations
      kind: article
      path: paper
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
